### ISSUE TITLE
More guidance to chairs around what is appropriate requirement for related implementation

### ISSUE THREAD

**Issue by dthaler** [eckelcu/draft-eckel-edm-find-code#5]
> The code must be publicly available, and preferably open source, though other terms of use may exist as well. 

As a WG chair, I would like to have more written policy for whether (say) product websites of closed source implementations might be ok to list.   Similarly, if the code is available to members of some other SDO so you have to pay to join the SDO first.  Etc.  Rather than each WG chair having to come up with their own policy, a BCP for chairs to use if they want would be helpful.

**Comment by eckelcu** [comment]
Addressed by #9
